name: 리뷰 요청 알림 - PR 오픈 시 Slack 알림 전송

on:
  pull_request:
    types: [opened] # PR이 처음 열릴 때만 작동

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification to Channel
        run: |
          PR_LABELS=$(echo '${{ toJson(github.event.pull_request.labels) }}')

          if echo "$PR_LABELS" | grep -q '"name":"draft"'; then
            echo "라벨에 'draft'가 포함되어 있어 알림을 생략합니다."
            exit 0
          fi

           # GitHub 사용자명과 Slack ID 매핑
          declare -A GITHUB_TO_SLACK
          GITHUB_TO_SLACK["JJJ-un"]="U0927V6KWTA"
          GITHUB_TO_SLACK["vlmubyd"]="U08J5DHJTK9"

          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_NUMBER=${{ github.event.pull_request.number }}

          curl -X POST \
            -H 'Content-type: application/json' \
            --data '{
              "text": ":bell: *새로운 PR이 오픈되었습니다!*",
              "attachments": [
                {
                  "color": "#439FE0",
                  "title": "#'"${PR_NUMBER}"' '"${PR_TITLE}"'",
                  "title_link": "'"${PR_URL}"'",
                  "text": "작성자: '"${PR_AUTHOR}"'"
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
